### ISSUE TITLE
Moon Calculations are wrong

### ISSUE THREAD

**Issue by MikecSimon** [kostebudinoski/SunCalcNet#2]
I get false data regarding moon calculations, according to MoonCalc.org (and TimeAndDate.com).
Moon rise, set, fraction, phase etc. are wrong for any given date and time.

**Comment by kostebudinoski** [comment]
Hey @MikecSimon !

Could you please provide more details? How are you using the lib? Could it be that for your method call you are setting the time of the date too? Try to do the call it with the date only, i.e. with the time set to 00:00:00.

I should add this at some point in the code, to set the time to midnight, before getting the moon times.

**Comment by kostebudinoski** [comment]
Fix in https://github.com/kostebudinoski/SunCalcNet/commit/e28a84b4e14dc9c54f06505947d084de38ef0e0e

Please use lib version 1.1.2

**Comment by MikecSimon** [comment]
either way i use the lib, the result stays the same as before.
Calculations are different to mooncalc (and dateandtime that uses their lib).
Can there be any constant that is misstyped?
For example:
lat: 45.9, lang: 14.4
(CET+2)
moonrise for 14.5.2020 --2:17:30
moonset for 14.5.2020 --11:59:53 
(third quarter: 14.5.2020 aprox. 16.46)

**Comment by kostebudinoski** [comment]
I think you are doing something wrong, please share your code. Here are my tests with version SunCalcNet 1.1.3 (check nuget for the latest package)

**SunCalcJs:**

`SunCalc.getMoonTimes(new Date(2020, 4, 15, 12, 16, 0), 45.9, 14.4)`

Result:
```
{
	rise: Fri May 15 2020 02:48:19 GMT+0200 (Mitteleuropäische Sommerzeit), 
	set: Fri May 15 2020 13:03:50 GMT+0200 (Mitteleuropäische Sommerzeit)
}
```

And here is a test from SunCalcNet that is passing:

```
[Fact]
public void Get_Moon_Times_Time_Specified_Returns_MoonRise_And_Set_Times_1()
{
	var date = new DateTime(2020, 5, 15, 12, 16, 0);
	var lat = 45.9;
	var lng = 14.4;
	
	var moonPhase = MoonCalc.GetMoonPhase(date, lat, lng);
	
	Assert.Equal("2020-05-15 02:48:19", moonPhase.Rise.Value.ToString("yyyy-MM-dd HH:mm:ss"));
	Assert.Equal("2020-05-15 13:03:50", moonPhase.Set.Value.ToString("yyyy-MM-dd HH:mm:ss"));
}
```
