### ISSUE TITLE
SunPhase time offset not correct.

### ISSUE THREAD

**Issue by CorEhrhardt** [kostebudinoski/SunCalcNet#3]
Hello Koste,

Your sun phase time is not correct. The offset is not calculated in your phase time.
If your offset is +2 hours or your offset is 4 hours, the phase time is for both the same.

By your moonphase calculation is the offset calculated in your phase time.

Can you look at the sun phase time?

With kind regards Cor

**Comment by kostebudinoski** [comment]
Hi Cor,

Can you share a code sample that produces the wrong calculation?

Offset is not part of the SunCalc library. Dates should be formatted depending on the timezone requirements in the client application logic. 

As far as I remember, [SunCalc JS](https://github.com/mourner/suncalc) Lib doesn't handle the offset too.

**Comment by kostebudinoski** [comment]
Not really, I should switch back to DateTime object everywhere as it was initially. Date time zones should be handled in client application logic

**Comment by kostebudinoski** [comment]
I updated all DateTimeOffset input parameters to DateTime.
You can switch to version [1.1.4](https://www.nuget.org/packages/SunCalcNet/1.1.4) which is already deployed.

**Comment by CorEhrhardt** [comment]
Thanx
