### ISSUE TITLE
Year in Date Time and it's impact of Sun Position

### ISSUE THREAD

**Issue by paireks** [kostebudinoski/SunCalcNet#6]
Hey! :)

First of all it's good to notice, that using SunCalcNet Sun's Analemma is changing through the years (that you can set in DateTime input), so if I increase the number of years it moves the whole Analemma little by little. If you compare year 2000 and 2500 you will see this difference. What I also noticed is a weird huge jump of Sun's Analemma between years 1899 and 1900. For some reason positions earlier than 1899 are completely different than these after. Looking at the source code it looks like it might be the thing with the ToJulianDate method.

Generally let me know which parts of it are probably bugs and which one are features :) Maybe creating some sort of a check if year in DateTime is in acceptable range will make sense.

Best regards,
Wojciech

**Comment by kostebudinoski** [comment]
Hi, 

thanks for your input. Could you please provide a failing unit test? What's the given result, and what's the expected result.

The ToJulianDate uses the .net ToOADate, which uses a different starting point (December 30, 1899), and thus I append the value of 2415018.5 (the Julian Date of midnight, December 30, 1899)

**Comment by paireks** [comment]
Hey @kostebudinoski!

I don't know what should be exactly for expected, but here is an example:

        [Fact]
        public void Get_Sun_Position_Returns_Azimuth_And_Altitude_For_The_Given_Time_And_Location_Before_And_After()
        {
            int startDate = 1850;
            var lat = 50.5;
            var lng = 30.5;

            for (int i = 0; i < 30; i++)
            {
                int currentYear = startDate + i * 4;
                var dateTime = new DateTime(currentYear, 3, 5, 0, 0, 0, DateTimeKind.Utc);
                var sunPosition = SunCalc.GetSunPosition(dateTime, lat, lng);
                    
                _testOutputHelper.WriteLine($"Current year: {currentYear}, " +
                                            $"Altitude: {sunPosition.Altitude.ToString(CultureInfo.InvariantCulture)}, " +
                                            $"Azimuth: {sunPosition.Azimuth.ToString(CultureInfo.InvariantCulture)}");
            }
        }

In results we get:

> Current year: 1850, Altitude: -0.6935819678151932, Azimuth: -2.534187414039249
> Current year: 1854, Altitude: -0.6936251217164552, Azimuth: -2.5333978051880166
> Current year: 1858, Altitude: -0.6936679610817575, Azimuth: -2.5326081218607355
> Current year: 1862, Altitude: -0.6937104858259692, Azimuth: -2.5318183644968775
> Current year: 1866, Altitude: -0.6937526958432418, Azimuth: -2.531028533466044
> Current year: 1870, Altitude: -0.6937945910276904, Azimuth: -2.530238629138383
> Current year: 1874, Altitude: -0.6938361713165595, Azimuth: -2.5294486520245125
> Current year: 1878, Altitude: -0.6938774365623401, Azimuth: -2.5286586023549233
> Current year: 1882, Altitude: -0.6939183867454812, Azimuth: -2.52786848078119
> Current year: 1886, Altitude: -0.6939590217297389, Azimuth: -2.527078287569589
> Current year: 1890, Altitude: -0.693999341421721, Azimuth: -2.5262880231270026
> Current year: 1894, Altitude: -0.69403934576051, Azimuth: -2.5254976879657267
> Current year: 1898, Altitude: -0.6940790346214172, Azimuth: -2.5247072823881855
> Current year: 1902, Altitude: -0.7007776195776706, Azimuth: -2.5218662109528704
> Current year: 1906, Altitude: -0.7008147291441441, Azimuth: -2.521070635972238
> Current year: 1910, Altitude: -0.7008515176572394, Azimuth: -2.5202749935067517
> Current year: 1914, Altitude: -0.7008879850375631, Azimuth: -2.519479284016454
> Current year: 1918, Altitude: -0.7009241311952045, Azimuth: -2.5186835079266134
> Current year: 1922, Altitude: -0.7009599560298991, Azimuth: -2.5178876656276348
> Current year: 1926, Altitude: -0.7009954594741443, Azimuth: -2.5170917576156833
> Current year: 1930, Altitude: -0.701030641428383, Azimuth: -2.51629578428182
> Current year: 1934, Altitude: -0.7010655018258705, Azimuth: -2.5154997461228352
> Current year: 1938, Altitude: -0.7011000405568778, Azimuth: -2.514703643495336
> Current year: 1942, Altitude: -0.7011342575445938, Azimuth: -2.5139074768615988
> Current year: 1946, Altitude: -0.7011681527234991, Azimuth: -2.5131112467192915
> Current year: 1950, Altitude: -0.7012017259848641, Azimuth: -2.5123149534260123
> Current year: 1954, Altitude: -0.7012349772530283, Azimuth: -2.511518597444944
> Current year: 1958, Altitude: -0.7012679064418086, Azimuth: -2.510722179204478
> Current year: 1962, Altitude: -0.7013005134707758, Azimuth: -2.5099256991508887
> Current year: 1966, Altitude: -0.7013327982599374, Azimuth: -2.5091291577307193

If we put it as a chart to visualize this jump, we get:
![2022-08-18_01h39_42](https://user-images.githubusercontent.com/47977819/185262488-fa42bfdd-b34f-4e38-916a-0e6b0cd11cdb.png)

![2022-08-18_01h39_53](https://user-images.githubusercontent.com/47977819/185262510-5dc000bf-5609-4ab6-b0ba-f1adaf9a7dd8.png)

I know that it is probably really rare for someone to analyze such things, but I kind of noticed this and wanted to point it out and share it ;) In unit tests I see only year 2013 analyzed, but in fact given year impacts the results, so it will be good to know if such impact is planned or not :)

Best regards,
Wojciech

**Comment by kostebudinoski** [comment]
if you generate the data for a longer period, you can notice that these jumps are happening every 100 years.

Here is a plot graph for the Altitude:

![image](https://user-images.githubusercontent.com/1423002/187901474-d947b3cb-09a6-43a9-bb72-f3fd21317bd6.png)

Not quite sure, if it's an issue or correct behaviour in the altitude.
